<a href="https://colab.research.google.com/github/Luke-Williams-01/Luke-Williams-01/blob/main/Project_Data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Imports
from pylab import *
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

In [2]:
# Reading in the data

C111,C112,C113,C114,C115,W111,W112,W113,W114,W115= np.loadtxt('Gr11.txt', usecols= [1,2,3,4,5,16,17,18,19,20], unpack = True, skiprows = 1, dtype = float)

C161,C162,C163,C164,C165,W161,W162,W163,W164,W165= np.loadtxt('Gr16.txt', usecols= [1,2,3,4,5,16,17,18,19,20], unpack = True, skiprows = 1, dtype = float)

In [3]:
# Analysis of the data

# Calculating mean spectra

# For Gr11 spectra
xbar111 = (C111[0]+C112[0]+C113[0]+C114[0]+C115[0])/5
print(xbar111)
xbar112 = (C111[1]+C112[1]+C113[1]+C114[1]+C115[1])/5
print(xbar112)
xbar113 = (C111[2]+C112[2]+C113[2]+C114[2]+C115[2])/5
print(xbar113)
xbar114 = (C111[3]+C112[3]+C113[3]+C114[3]+C115[3])/5
print(xbar114)
xbar115 = (C111[4]+C112[4]+C113[4]+C114[4]+C115[4])/5
print(xbar115)
xbar116 = (C111[5]+C112[5]+C113[5]+C114[5]+C115[5])/5
print(xbar116)
xbar117 = (C111[6]+C112[6]+C113[6]+C114[6]+C115[6])/5
print(xbar117)

3917.97
4304.978000000001
4776.2339999999995
5049.688
5385.188
6256.858
6896.82


In [4]:
# For Gr16 spectra
xbar161 = (C161[0]+C162[0]+C163[0]+C164[0]+C165[0])/5
print(xbar161)
xbar162 = (C161[1]+C162[1]+C163[1]+C164[1]+C165[1])/5
print(xbar162)
xbar163 = (C161[2]+C162[2]+C163[2]+C164[2]+C165[2])/5
print(xbar163)
xbar164 = (C161[3]+C162[3]+C163[3]+C164[3]+C165[3])/5
print(xbar164)

6248.726
6896.0779999999995
7621.280000000001
8366.044


In [5]:
def func(a, b):
    return (b/(a + (b/2))) * 3e5

V111 = func(a = C111, b = W111)
print(V111)
V112 = func(a = C112, b = W112)
print(V112)
V113 = func(a = C113, b = W113)
print(V113)
V114 = func(a = C114, b = W114)
print(V114)
V115 = func(a = C115, b = W115)
print(V115)

V161 = func(a = C161, b = W161)
print(V161)
V162 = func(a = C162, b = W162)
print(V162)
V163 = func(a = C163, b = W163)
print(V163)
V164 = func(a = C164, b = W164)
print(V164)
V165 = func(a = C165, b = W165)
print(V165)


[ 6513.06026587  9622.81491914 11033.53850329 10631.75194137
 21754.24125039  8497.57446509  3212.5384249 ]
[ 6286.36499975  9379.86747878 10762.18810612 10789.93795932
  8190.75354933  9109.95012686  3659.57232233]
[ 6185.63132639  9087.37330984 10845.43862678 11098.06498268
  8938.12155105  9103.99139731  4033.51183279]
[ 6115.95714996  9327.22796157 11022.51792881  9770.65612427
  5185.30388511  4796.52406502  3885.59676294]
[ 5890.26231078  9495.97078303 10555.33836752 10144.53581505
  6224.48998361  3783.37253831  2957.07692441]
[ 5523.94342114  6970.07087311  2356.72166381 14234.09422726]
[ 6059.1417716   3687.37295768  2362.82982882 14737.65234721]
[ 5442.13591556  3753.11389952  2365.15734719 12453.27818897]
[ 8632.19270343  3454.04028343  2342.16950606 12401.89175826]
[ 7993.86598314  3112.02106723  2262.80721432 11066.57443543]


In [6]:
# Calculating mean velocities (km/s)

# For Gr11
Vxbar111 = (V111[0]+V112[0]+V113[0]+V114[0]+V115[0])/5
print(Vxbar111)
Vxbar112 = (V111[1]+V112[1]+V113[1]+V114[1]+V115[1])/5
print(Vxbar112)
Vxbar113 = (V111[2]+V112[2]+V113[2]+V114[2]+V115[2])/5
print(Vxbar113)
Vxbar114 = (V111[3]+V112[3]+V113[3]+V114[3]+V115[3])/5
print(Vxbar114)
Vxbar115 = (V111[4]+V112[4]+V113[4]+V114[4]+V115[4])/5
print(Vxbar115)
Vxbar116 = (V111[5]+V112[5]+V113[5]+V114[5]+V115[5])/5
print(Vxbar116)
Vxbar117 = (V111[6]+V112[6]+V113[6]+V114[6]+V115[6])/5
print(Vxbar117)

6198.255210550226
9382.650890472312
10843.804306503667
10486.989364536597
10058.582043898354
7058.282518515976
3549.6592534740325


In [8]:
# For Gr16
Vxbar161 = (V161[0]+V162[0]+V163[0]+V164[0]+V165[0])/5
print(Vxbar161)
Vxbar162 = (V161[1]+V162[1]+V163[1]+V164[1]+V165[1])/5
print(Vxbar162)
Vxbar163 = (V161[2]+V162[2]+V163[2]+V164[2]+V165[2])/5
print(Vxbar163)
Vxbar164 = (V161[3]+V162[3]+V163[3]+V164[3]+V165[3])/5
print(Vxbar164)

6730.255958973187
4195.323816194912
2337.937112038123
12978.698191427264
